version: "3"
services:
  mongo:
    image: "mongo:5"
    ports:
      - 27017:27017
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  main-server:
    container_name: main-server-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=development
    ports:
      - 3888:80
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis

networks:
  front-tier:
    driver: bridge
